version: '3.5'

networks:
   web-app-net:
       name: my-web-app-net
       #driver: overlay
       driver: bridge

services:
   webapp-admin:
       image: itsoulltd/itracker-images:vaadin-app-1.0
       build:
          context: .
          dockerfile: Dockerfile-embedded
       environment:
          com.itsoul.lab.api.public.dns: itracker-external-o35sj8s1xz98-1208457667.ap-southeast-1.elb.amazonaws.com
          app.db.name: /api/shareable
          app.db.host: itracker-external-o35sj8s1xz98-1208457667.ap-southeast-1.elb.amazonaws.com
          app.db.port: 8083
          app.tenant.username: mail.dailygoods@gmail.com
          app.tenant.password: Itsoul@1
          app.db.auth.name: /auth-service/auth
          app.db.auth.host: itracker-external-o35sj8s1xz98-1208457667.ap-southeast-1.elb.amazonaws.com
          app.db.auth.port: 8080
       ports:
          - 8080:8080
       restart: on-failure
       networks:
          - web-app-net