spring.application.name=SpringHttpClientStarter
server.app.domain=localhost
server.port=8080

# WebClient config:
web.client.base-url=https://mydomain.com
web.client.username=my-username
web.client.password=*****
web.client.in-memory.buffer.size.in-mb=5

# ocr-tesseract config
ocr.enable=false
#ocr.tessdata-path=tessdata
#ocr.language=eng+deu

# Local-DirPaths:
# For-Mac+Linus:
#app.home.logs=/Users/${USER}/Logs
#app.upload.dir=/Users/${USER}/Downloads
# For-Windows:
app.home.logs=/Users/Public/Logs
app.upload.dir=/Users/Public/Downloads
