spring.application.name=SpringHttpClientStarter
server.app.domain=localhost
server.port=8080

# ocr-tesseract config
ocr.enable=false
#ocr.tessdata-path=tessdata
#ocr.language=eng+deu

# Local-DirPaths:
# For-Mac+Linus:
#app.home.logs=/Users/${USER}/Logs
#app.upload.dir=/Users/${USER}/Downloads
# For-Windows:
app.home.logs=/Users/Public/Logs
app.upload.dir=/Users/Public/Downloads
