version: '3.5'

networks:
   web-app-net:
       name: my-web-app-net
       #driver: overlay
       driver: bridge

volumes:
  auth-db-storage:

services:
  auth-db:
    image: mysql:8.0.13
    environment:
      MYSQL_DATABASE: authDB
      MYSQL_ROOT_PASSWORD: root@123
    ports:
      - 3307:3306
    networks:
      - web-app-net
    volumes:
      - auth-db-storage:/var/lib/mysql

##End of Scripts