version: '3.5'

networks:
  web-app-net:
    name: my-web-app-net
    #driver: overlay
    driver: bridge

volumes:
  cassandra-db-storage:

services:
  cassandra-db:
    image: cassandra:latest
    ports:
      - 9042:9042
    networks:
      - web-app-net
    volumes:
      - cassandra-db-storage:/var/lib/cassandra

  webapp:
    image: spring-microservice-with-cassandra-starter:1.0
    build:
      context: .
      #dockerfile: Dockerfile
      dockerfile: Dockerfile-embedded
    environment:
      cassandra.db.keyspace: cassandradb
      cassandra.db.host: cassandra-db
      cassandra.db.port: 9042
      management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
      app.home.logs: /home/logs
      app.upload.dir: /home/downloads
    ports:
      - 8080:8080
    depends_on:
      - cassandra-db
    restart: on-failure
    networks:
      - web-app-net

##End of Scripts