version: '3.5'

networks:
   web-app-net:
       name: my-web-app-net
       #driver: overlay
       driver: bridge

volumes:
   mysql-db-storage:
   redis-inmemory-storage:

services:
   mysql-db:
      image: mysql:8.0.13
      environment:
          MYSQL_DATABASE: testDB
          MYSQL_ROOT_PASSWORD: root
      ports:
          - 3306:3306
      networks:
          - web-app-net
      volumes:
          - mysql-db-storage:/var/lib/mysql

   redis:
      image: redis:latest
      ports:
         - 6379:6379
      networks:
         - web-app-net
      volumes:
         - redis-inmemory-storage:/data

   zookeeper:
      image: bitnami/zookeeper:latest
      ports:
        - 2181:2181
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
      networks:
        - web-app-net

   kafka:
      image: bitnami/kafka:latest
      ports:
        - 9092:9092
      environment:
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        #For Debug Only: Place Device-Current IP:
        - KAFKA_ADVERTISED_LISTENERS= PLAINTEXT://192.168.0.18:9092
        #
      depends_on:
        - zookeeper
      networks:
        - web-app-net

##End Of Scripts