version: '3.5'

networks:
   web-app-net:
       name: my-web-app-net
       #driver: overlay
       driver: bridge

services:
   webapp-admin:
       image: itsoulltd/itracker-images:vaadin-app-1.0
       build:
          context: .
          dockerfile: Dockerfile-embedded
       environment:
          com.itsoul.lab.api.public.dns: localhost
          app.db.name: /api/shareable
          app.db.host: localhost
          app.db.port: 8083
          app.tenant.username: demo@gmail.com
          app.tenant.password: mypass@123
          app.db.auth.name: /auth-service/auth
          app.db.auth.host: localhost
          app.db.auth.port: 8080
       ports:
          - 8080:8080
       restart: on-failure
       networks:
          - web-app-net